---
- name: Ensure snapd is installed.
  package:
    name: snapd
    state: present
  register: snapd_install

- name: Ensure snapd is enabled.
  systemd:
    name: snapd.socket
    enabled: true
# fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "src file does not exist, use \"force=yes\" 
#if you really want to create the link: /var/lib/snapd/snap", "owner": "root", "path": "/snap", "size": 4096, "src": "/var/lib/snapd/snap", "state": "directory", "uid": 0}
#- name: Enable classic snap support.
#  file:
#    src: /var/lib/snapd/snap
#    dest: /snap
#    force: yes
#    state: link

- name: Update snap after install.
  shell: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_install is changed

- name: Install certbot via snap.
  snap:
    name: certbot
    classic: true

- name: Symlink certbot into place.
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Set Certbot script variable.
  set_fact:
    certbot_script: /usr/bin/certbot
